### ISSUE TITLE
Update for Legion

### ISSUE THREAD

**Issue by Gorthezar** [aduth/Doom_CooldownPulse#2]
Is this addon dead?

**Comment by aduth** [comment]
I don't play World of Warcraft anymore, so don't have plans to add feature enhancements to the addon. That said, I took it for a spin yesterday and it seems to work fine assuming you load out-of-date addons. Are you experiencing breaking issues?

I can plan to put together a ToC update so it at least shows as up-to-date.

**Comment by Gorthezar** [comment]
Not having any real problems just wanted to see if it would ever get at least even a ToC update as you mentioned.

**Comment by solor** [comment]
all going well on 7.0.3, only need a toc update.

**Comment by aduth** [comment]
Closed by 940f57e01dbd472e0698650287ef1812f4ea459c

**Comment by aduth** [comment]
Pushed new version 1.12.13 to both Curse and WoWInterface
