### ISSUE TITLE
sound file is missing

### ISSUE THREAD

**Issue by Solor** [aduth/Doom_CooldownPulse#3]
line 148, sound file is missing.

**Comment by aduth** [comment]
I appreciate the extra pair of eyes in auditing the code, @solor 😃  I'd noticed this too in my latest set of revisions, but then recalled that it was originally added as an opt-in feature for people who were missing the sound from JIM's original cooldown pulse addon.

From the [v1.2 release notes](https://mods.curse.com/addons/wow/doomcooldownpulse#t1:changes):

>New! Missed the old heart-beat sound from JIM's Cooldown Pulse? Drag the lubdub.wav sound file from JIM's addon into the Doom_CooldownPulse folder and you now have a sound notification

Not exactly the most discoverable feature. Ideally we'd just include the sound file and add an option to the configuration screen.

**Comment by wyngman** [comment]
Any chance someone is going to update this for Legion?

**Comment by Genimal** [comment]
I postet same thing on curse.com

Step 1.
Open your Doom_CooldownPulse.lua

Step 2.
You have to fix 2 lines.

Line422:PlaySound("igMainMenuOption")
->replace to
PlaySound(852)
 
Line366: local newState = (self:GetChecked() == 1) or nil
->replace to
local newState;if self:GetChecked() then newState=true else newState=false end

**Comment by aduth** [comment]
Originally fixed by #4 

Sound file was removed in 357e8133e02875e364501d6c0dbe5435d37663a1
